### ISSUE TITLE
Disable Spike commit logging debug output

### ISSUE THREAD

**Issue by jserv** [mathis-s/SoomRV#15]
In the `README.md` file, it is mentioned that the system achieves 8.333 DMIPS/MHz. However, when I simulate using the command `obj_dir/VTop test_programs/dhry_1.s`, it executes 134733 cycles. Could you please guide me on how to obtain the Dhrystone benchmark score?

I meant, it is frustrating to extract relevant information from the output of the aforementioned command.
```
...
5core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
6
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
core   0: 3 0x80000024 (0xa001)
134733 cycles
```

**Comment by mathis-s** [comment]
Sadly Spike generates a lot of messages when commit logging is enabled, commit logging is required for cosimulation though. However, all of this output is on `stderr`, which you can redirect to `/dev/null`.

You can also apply following hack to disable the log output entirely.
```
diff --git a/riscv/execute.cc b/riscv/execute.cc
index acf0e908..a3416adc 100644
--- a/riscv/execute.cc
+++ b/riscv/execute.cc
@@ -62,6 +62,7 @@ static void commit_log_print_value(FILE *log_file, int width, uint64_t val)

 static void commit_log_print_insn(processor_t *p, reg_t pc, insn_t insn)
 {
+  return;
   FILE *log_file = p->get_log_file();
 
   auto& reg = p->get_state()->log_reg_write;
diff --git a/riscv/mmu.h b/riscv/mmu.h
```

For a proper fix, I will have to fork Spike at some point.

**Comment by jserv** [comment]
> Sadly Spike generates a lot of messages when commit logging is enabled, commit logging is required for cosimulation though. However, all of this output is on `stderr`, which you can redirect to `/dev/null`.

Can you add something like command `obj_dir/VTop test_programs/dhry_1.s 2> /dev/null` in `README.md`? So that, people can obtain the results.

My results on AMD Ryzen Threadripper 2990WX 32-Core Processor.
```
Runtime (cycles) 110994
Executed (instrs) 302040
mIPC 2721
mDMIPS/MHz 10256
```

**Comment by mathis-s** [comment]
Good point, done. The simulator is not using any measurements of real time, so the score should be identical everywhere. I've updated and clarified the score in `README.md` as well. Thanks again!
