### ISSUE TITLE
Mention license terms in top-level documentation

### ISSUE THREAD

**Issue by jserv** [mathis-s/SoomRV#17]
At present, the `README.md` file lacks explicit licensing information. I would suggest adding the following information to address this:
> ## License
> `SoomRV` is released under the MIT License. Use of this source code is governed by a MIT-style license that can be found in the `LICENSE` file.
> 
> ### External Source Code
> * `riscv-isa-sim` (aka `Spike`): released under the 3-Clause BSD License, used in conjunction with the simulator.
> * `hardfloat` : released under the 3-Clause BSD License.

By including this section in the `README.md`, users will have clear visibility and understanding of the licensing terms associated with the project and any external source code used.

**Comment by mathis-s** [comment]
I have appended your snippet to `README.md`, thanks!
