### ISSUE TITLE
Error while runing "make soomrv" command

### ISSUE THREAD

**Issue by Jeremy-Jia** [mathis-s/SoomRV#25]
Hi, I'm using v5.008 on ubuntu-20.04 , error occurs when run make：
<img width="867" alt="image" src="https://github.com/mathis-s/SoomRV/assets/36725890/523becff-bfc9-4634-91d4-33d71fe61f51">

**Comment by Jeremy-Jia** [comment]
Verilator 5.017 works

**Comment by mathis-s** [comment]
Thanks for finding a fix! Interestingly, I'm also using v5.008. I imagine there are some packaging differences between Ubuntu and Manjaro changing some default flags (ccache is also not on by default for me).
