### ISSUE TITLE
device-tree-compiler not found

### ISSUE THREAD

**Issue by Chiwawachiwawa** [mathis-s/SoomRV#26]
Hello Sir,when I using  'make setup',something went wrong,
the info shown below:

```
soomrvver@soomrvver:~/SoomRV$ make setup
git submodule update --init --recursive
cd riscv-isa-sim && ./configure --with-boost=no --with-boost-asio=no --with-boost-regex=no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for ar... ar
checking for ranlib... ranlib
checking for dtc... no
configure: error: device-tree-compiler not found
make: *** [Makefile:91：setup] 錯誤 1
soomrvver@soomrvver:~/SoomRV$ 
```

my verilator

```
soomrvver@soomrvver:~/SoomRV$ verilator -version
Verilator 5.016 2023-09-16 rev v5.014-149-g57c816f90
soomrvver@soomrvver:~/SoomRV$
```

my gcc-version

```
soomrvver@soomrvver:~/SoomRV$ riscv32-unknown-linux-gnu-gcc -v 
Using built-in specs.
COLLECT_GCC=riscv32-unknown-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/home/soomrvverncku/SoomRV/riscv-gnu-toolchain/libexec/gcc/riscv32-unknown-linux-gnu/12.2.0/lto-wrapper
Target: riscv32-unknown-linux-gnu
--with-system-zlib --enable-shared --enable-tls --enable-languages=c,c++,fortran --disable-libmudflap --disable-libssp --disable-libquadmath --disable-libsanitizer --disable-nls --disable-bootstrap --src=.././gcc --disable-multilib --with-abi=ilp32d --with-arch=rv32gc --with-tune=rocket --with-isa-spec=20191213 'CFLAGS_FOR_TARGET=-O2    -mcmodel=medlow' 'CXXFLAGS_FOR_TARGET=-O2    -mcmodel=medlow'
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 12.2.0 (g2ee5e430018) 
soomrvver@soomrvver:~/SoomRV$ 
```

Is there something wrong with my tools(?
Thank's a lot!!

**Comment by mathis-s** [comment]
Hi! Seems to me like you're just missing `device-tree-compiler`.

In the [GitHub workflow](https://github.com/mathis-s/SoomRV/blob/master/.github/workflows/makefile.yml), this command is used to install all additional dependencies (including `device-tree-compiler`):
`sudo apt-get install device-tree-compiler libfl2 libfl-dev zlib1g zlib1g-dev numactl git help2man perl python3 make`

That should hopefully fix it. Let me know if there's any other issues!

**Comment by Chiwawachiwawa** [comment]
> Hi! Seems to me like you're just missing `device-tree-compiler`.
> 
> In the [GitHub workflow](https://github.com/mathis-s/SoomRV/blob/master/.github/workflows/makefile.yml), this command is used to install all additional dependencies (including `device-tree-compiler`): `sudo apt-get install device-tree-compiler libfl2 libfl-dev zlib1g zlib1g-dev numactl git help2man perl python3 make`
> 
> That should hopefully fix it. Let me know if there's any other issues!

It worked !
But I met another problem,my memory seems not enought to do ''' make setup ''' ,it crashed after a few minutes running.
How should I modify the makefile codes to limit the usage of the case?
Thank's a lot !!

**Comment by mathis-s** [comment]
If it's during setup, the spike build is likely what's using too much memory. You can reduce it to just one job like this:
```diff
--- a/Makefile
+++ b/Makefile
@@ -92,7 +92,7 @@ trace: soomrv
 setup:
        git submodule update --init --recursive
        cd riscv-isa-sim && ./configure --with-boost=no --with-boost-asio=no --with-boost-regex=no
-       make -j $(nproc) -C riscv-isa-sim
+       make -j 1 -C riscv-isa-sim
 .PHONY: clean
 clean:
        $(RM) -r obj_dir
```


That should fix `make setup`, you might also need to set verilator to only use on thread for regular `make`:
```diff
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,7 @@ VERILATOR_FLAGS = \
        -Wno-PINCONNECTEMPTY -Wno-DECLFILENAME --x-assign unique --x-initial unique -O3 -sv \
        -CFLAGS "-march=native" \
        -LDFLAGS "-ldl" \
-       -MAKEFLAGS -j16
+       -MAKEFLAGS -j1
```

This will make building quite slow, you may want to try using more than one job depending on how much RAM is still available.

**Comment by Chiwawachiwawa** [comment]
> If it's during setup, the spike build is likely what's using too much memory. You can reduce it to just one job like this:
> 
> ```diff
> --- a/Makefile
> +++ b/Makefile
> @@ -92,7 +92,7 @@ trace: soomrv
>  setup:
>         git submodule update --init --recursive
>         cd riscv-isa-sim && ./configure --with-boost=no --with-boost-asio=no --with-boost-regex=no
> -       make -j $(nproc) -C riscv-isa-sim
> +       make -j 1 -C riscv-isa-sim
>  .PHONY: clean
>  clean:
>         $(RM) -r obj_dir
> ```
> 
> That should fix `make setup`, you might also need to set verilator to only use on thread for regular `make`:
> 
> ```diff
> --- a/Makefile
> +++ b/Makefile
> @@ -3,7 +3,7 @@ VERILATOR_FLAGS = \
>         -Wno-PINCONNECTEMPTY -Wno-DECLFILENAME --x-assign unique --x-initial unique -O3 -sv \
>         -CFLAGS "-march=native" \
>         -LDFLAGS "-ldl" \
> -       -MAKEFLAGS -j16
> +       -MAKEFLAGS -j1
> ```
> 
> This will make building quite slow, you may want to try using more than one job depending on how much RAM is still available.

Thanks,I'll try it!!

**Comment by Chiwawachiwawa** [comment]
`%Warning-GENUNNAMED: hardfloat/HardFloat_rawFN.v:177:22: Unnamed generate block 'genblk1' (IEEE 1800-2017 27.6)                                                       : ... Suggest assign a label with 'begin : gen_<label_name>'
  177 |             end else begin
      |                      ^~~~~
%Error: Exiting due to 16 warning(s)`
Sorry for bothing you again,I done the `make setup` step,but when I do `make`,it got something wrong again,how can I fix this problem?
Thanks a lot!

**Comment by mathis-s** [comment]
Don't worry! This is a common error when using a new version of Verilator (I'm still using 5.008). They often add new warnings in the new version which the old version didn't detect. Usually you can just ignore the new warnings by adding (in this case) `-Wno-GENUNNAMED`.
```diff
--- a/Makefile
+++ b/Makefile
@@ -1,9 +1,9 @@
 VERILATOR_FLAGS = \
        --cc --build --threads 4 --unroll-stmts 999999 -unroll-count 999999 --assert -Wall -Wno-BLKSEQ -Wno-UNUSED \
-       -Wno-PINCONNECTEMPTY -Wno-DECLFILENAME --x-assign unique --x-initial unique -O3 -sv \
+       -Wno-PINCONNECTEMPTY -Wno-DECLFILENAME -Wno-GENUNNAMED --x-assign unique --x-initial unique -O3 -sv \
        -CFLAGS "-march=native" \
        -LDFLAGS "-ldl" \
```

**Comment by Chiwawachiwawa** [comment]
> Don't worry! This is a common error when using a new version of Verilator (I'm still using 5.008). They often add new warnings in the new version which the old version didn't detect. Usually you can just ignore the new warnings by adding (in this case) `-Wno-GENUNNAMED`.
> 
> ```diff
> --- a/Makefile
> +++ b/Makefile
> @@ -1,9 +1,9 @@
>  VERILATOR_FLAGS = \
>         --cc --build --threads 4 --unroll-stmts 999999 -unroll-count 999999 --assert -Wall -Wno-BLKSEQ -Wno-UNUSED \
> -       -Wno-PINCONNECTEMPTY -Wno-DECLFILENAME --x-assign unique --x-initial unique -O3 -sv \
> +       -Wno-PINCONNECTEMPTY -Wno-DECLFILENAME -Wno-GENUNNAMED --x-assign unique --x-initial unique -O3 -sv \
>         -CFLAGS "-march=native" \
>         -LDFLAGS "-ldl" \
> ```

Got it!
But after that I met an error seems like some module has been changed `../Top_tb.cpp:19:10: fatal error: VTop_RenameTable__N8.h:no such file or dictionary`
or maybe I just need to change the version of verilator(?

**Comment by mathis-s** [comment]
Yeah, this is another Verilator version difference :smile: In this case the include file name has changed, you can change it from `VTop_RenameTable__N8.h` to `VTop_RenameTable.h`.

**Comment by Chiwawachiwawa** [comment]
> Yeah, this is another Verilator version difference 😄 In this case the include file name has changed, you can change it from `VTop_RenameTable__N8.h` to `VTop_RenameTable.h`.

Thanks a lot!!I just changed the verilator's version,then it works!
