### ISSUE TITLE
Make linux errors

### ISSUE THREAD

**Issue by Chiwawachiwawa** [mathis-s/SoomRV#28]
`%Error: /usr/local/share/verilator/include/verilated.cpp:2533: VerilatedContext has 1 threads but model 'VTop' (instantiated as 'TOP') was Verilated with --threads 4.`
Hello,I had changed my verilator's version to 5.008 ,after that I stuck in 'make linux' with such error,I'd like to know how can I fix it, thank you!!

**Comment by mathis-s** [comment]
Sure, I think just need to set the threads for the verilator model to 1 like this:
```diff
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
 VERILATOR_FLAGS = \
-       --cc --build --threads 4 --unroll-stmts 999999 -unroll-count 999999 --assert -Wall -Wno-BLKSEQ -Wno-UNUSED \
+       --cc --build --threads 1 --unroll-stmts 999999 -unroll-count 999999 --assert -Wall -Wno-BLKSEQ -Wno-UNUSED \
        -Wno-PINCONNECTEMPTY -Wno-DECLFILENAME --x-assign unique --x-initial unique -O3 -sv \
        -CFLAGS "-march=native" \
        -LDFLAGS "-ldl" \
```
Let me know how it goes!

**Comment by Chiwawachiwawa** [comment]
> Sure, I think just need to set the threads for the verilator model to 1 like this:
> 
> ```diff
> --- a/Makefile
> +++ b/Makefile
> @@ -1,5 +1,5 @@
>  VERILATOR_FLAGS = \
> -       --cc --build --threads 4 --unroll-stmts 999999 -unroll-count 999999 --assert -Wall -Wno-BLKSEQ -Wno-UNUSED \
> +       --cc --build --threads 1 --unroll-stmts 999999 -unroll-count 999999 --assert -Wall -Wno-BLKSEQ -Wno-UNUSED \
>         -Wno-PINCONNECTEMPTY -Wno-DECLFILENAME --x-assign unique --x-initial unique -O3 -sv \
>         -CFLAGS "-march=native" \
>         -LDFLAGS "-ldl" \
> ```
> 
> Let me know how it goes!

Thanks for your reply!!
I use 'sudo make linux' because 'make linux' would come out whit 'cannot open output file VTop' .
Hi,I had changed the contents,after that here comes some problems like below:
```
./obj_dir/VTop --device-tree=test_programs/linux/device_tree.dtb --backup-file=soomrv.backup test_programs/linux/linux_image.elf
ERROR 4
time=40134
ir=00009f2e ppc=80000188 inst=05072b83 sqn=2f
x00=00000000 x01=80000164 x02=80030000 x03=00000000 x04=00000000 x05=83f00000 x06=00000000 x07=00000000 
x08=00000000 x09=83f00000 x10=00000000 x11=83f00000 x12=00000000 x13=00000000 x14=80020140 x15=00000000 
x16=00000000 x17=00000000 x18=00000000 x19=00000000 x20=00000000 x21=00002000 x22=00000000 x23=00000000 
x24=00000000 x25=00000000 x26=00000000 x27=00000000 x28=00000000 x29=00000000 x30=00000000 x31=00000000 


SHOULD BE
mstatus=00000000 mepc=00000000 mcause=00000000 mtvec=80000410 mideleg=00000000 medeleg=00000000 mie=00000000 mip=00000000
ir=00009f2e ppc=80000188 pc=8000018c priv=3
x00=00000000 x01=80000164 x02=80030000 x03=00000000 x04=00000000 x05=83f00000 x06=00000000 x07=00000000 
x08=00000000 x09=83f00000 x10=00000000 x11=83f00000 x12=00000000 x13=00000000 x14=80020140 x15=00000000 
x16=00000000 x17=00000000 x18=00000000 x19=00000000 x20=00000000 x21=00002000 x22=00000000 x23=00000001 
x24=00000000 x25=00000000 x26=00000000 x27=00000000 x28=00000000 x29=00000000 x30=00000000 x31=00000000 
make: *** [Makefile:85：linux] error 255

```
should I had to remove some files to solve this problem(?

**Comment by mathis-s** [comment]
This might be an actual bug in SoomRV (`ERROR 4` means an instruction produced the wrong result), so thanks for the report! The current commit (`35a3613e95cc0806ef28debf21eb299dc64d2ecc`) in `master` works fine for me though:
```
./obj_dir/VTop --device-tree=test_programs/linux/device_tree.dtb --backup-file=soomrv.backup test_programs/linux/linux_image.elf

OpenSBI v1.2
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|___/_____|
        | |
        |_|

Platform Name             : platform-name
Platform Features         : medeleg
Platform HART Count       : 1
Platform IPI Device       : aclint-mswi
Platform Timer Device     : aclint-mtimer @ 1000000Hz
Platform Console Device   : uart8250
Platform HSM Device       : ---
Platform PMU Device       : ---
Platform Reboot Device    : ---
Platform Shutdown Device  : ---
Platform Suspend Device   : ---
Platform CPPC Device      : ---
Firmware Base             : 0x80000000
Firmware Size             : 192 KB
Firmware RW Offset        : 0x20000
Runtime SBI Version       : 1.0

Domain0 Name              : root
Domain0 Boot HART         : 0
Domain0 HARTs             : 0*
Domain0 Region00          : 0x11008000-0x1100bfff M: (I,R,W) S/U: ()
Domain0 Region01          : 0x11000000-0x11007fff M: (I,R,W) S/U: ()
Domain0 Region02          : 0x80020000-0x8002ffff M: (R,W) S/U: ()
Domain0 Region03          : 0x80000000-0x8001ffff M: (R,X) S/U: ()
Domain0 Region04          : 0x00000000-0xffffffff M: (R,W,X) S/U: (R,W,X)
Domain0 Next Address      : 0x80400000
Domain0 Next Arg1         : 0x82200000
Domain0 Next Mode         : S-mode
Domain0 SysReset          : yes
Domain0 SysSuspend        : yes

Boot HART ID              : 0
Boot HART Domain          : root
Boot HART Priv Version    : v1.12
Boot HART Base ISA        : rv32imacbx
Boot HART ISA Extensions  : time
Boot HART PMP Count       : 0
Boot HART PMP Granularity : 0
Boot HART PMP Address Bits: 0
Boot HART MHPM Count      : 0
Boot HART MIDELEG         : 0x00000222
Boot HART MEDELEG         : 0x0000b109
[    0.000000] Linux version 6.3.4 (m@m-desktop) (riscv32-buildroot-linux-gnu-gcc.br_real (Buildroot -g35a3613) 11.3.0, GNU ld (GNU Binutils) 2.38) #2 Mon Oct  9 20:05:44 CEST 2023
[    0.000000] OF: fdt: Ignoring memory range 0x80000000 - 0x80400000
[    0.000000] Machine model: riscv-minimal
[    0.000000] earlycon: uart8250 at MMIO 0x10000000 (options '1000000')
[    0.000000] printk: bootconsole [uart8250] enabled
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000080400000-0x0000000083ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
```
I also changed the Makefile to only use on thread. Can you tell me what commit you are using and which files you modified?

**Comment by Chiwawachiwawa** [comment]
Thanks! I only modified below!
```
--- a/Makefile
+++ b/Makefile



> -       --cc --build --threads 4 --unroll-stmts 999999 -unroll-count 999999 --assert -Wall -Wno-BLKSEQ -Wno-UNUSED \
> +       --cc --build --threads 1 --unroll-stmts 999999 -unroll-count 999999 --assert -Wall -Wno-BLKSEQ -Wno-UNUSED \

> -       make -j $(nproc) -C riscv-isa-sim
> +       make -j 1 -C riscv-isa-sim



>  -       -MAKEFLAGS -j16
> +       -MAKEFLAGS -j1


```
or maybe I should re-compile all files(I didn't do that after I modified the Makefile)

**Comment by mathis-s** [comment]
Hmm, it still works for me with those modifications. Maybe try cloning a fresh version of the repo and re-compile everything. If that still doesn't work, please do this:

1. Run `make trace` to build a Verilator model that generates traces
2. Run `./obj_dir/VTop --device-tree=test_programs/linux/device_tree.dtb --backup-file=soomrv.backup test_programs/linux/linux_image.elf` again
3. This generates `Top_tb.vcd`, please send that file to me

Let me know how it goes!

**Comment by Chiwawachiwawa** [comment]
It works pretty good,I also modifyed SoomRV/test_programs/linux/buildroot/support/dependencies/dependencies.sh
with few lines
```
#(*::*|*:.:*)
#	echo
#	echo "You seem to have the current working directory in your"
#	echo "PATH environment variable. This doesn't work."
#	exit 1
#	;;
```
to solve errors below:
```
You seem to have the current working directory in your
PATH environment variable. This doesn't work.
make[3]: *** [support/dependencies/dependencies.mk:27：dependencies] 錯誤 1
make[2]: *** [Makefile:82：_all] 錯誤 2
make[2]: 離開目錄「/home/soomrvverncku/SoomRV/test_programs/linux/buildroot」
make[1]: *** [Makefile:26：buildroot/output/images/Image] 錯誤 2
make[1]: 離開目錄「/home/soomrvverncku/SoomRV/test_programs/linux」
make: *** [Makefile:85：linux] 錯誤 2
```

**Comment by Chiwawachiwawa** [comment]
I had

**Comment by jserv** [comment]
> to solve errors below:
> ```
> You seem to have the current working directory in your
> PATH environment variable. This doesn't work.
> make[3]: *** [support/dependencies/dependencies.mk:27：dependencies] 錯誤 1
> make[2]: *** [Makefile:82：_all] 錯誤 2
> make[2]: 離開目錄「/home/soomrvverncku/SoomRV/test_programs/linux/buildroot」
> make[1]: *** [Makefile:26：buildroot/output/images/Image] 錯誤 2
> make[1]: 離開目錄「/home/soomrvverncku/SoomRV/test_programs/linux」
> make: *** [Makefile:85：linux] 錯誤 2
> ```

@Chiwawachiwawa , Next time, you can run `export LC_ALL=C` before the shell commands to eliminate localized messages, ensuring that only English characters appear in the terminal.

**Comment by Chiwawachiwawa** [comment]
> > to solve errors below:
> > ```
> > You seem to have the current working directory in your
> > PATH environment variable. This doesn't work.
> > make[3]: *** [support/dependencies/dependencies.mk:27：dependencies] 錯誤 1
> > make[2]: *** [Makefile:82：_all] 錯誤 2
> > make[2]: 離開目錄「/home/soomrvverncku/SoomRV/test_programs/linux/buildroot」
> > make[1]: *** [Makefile:26：buildroot/output/images/Image] 錯誤 2
> > make[1]: 離開目錄「/home/soomrvverncku/SoomRV/test_programs/linux」
> > make: *** [Makefile:85：linux] 錯誤 2
> > ```
> 
> Next time, you can run `export LC_ALL` before the shell commands to eliminate localized messages, ensuring that only English characters appear in the terminal.

Ok sir,I'll remember that!!
